### ISSUE TITLE
does not work with Cyrillic

### ISSUE THREAD

**Issue by atakishiev** [DiceBear/avatars#30]
It worked first, but not now
https://avatars.dicebear.com/v2/initials/A%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80.svg

**Comment by FlorianKoerner** [comment]
Thank you for the hint. Solved.

**Comment by smeijer** [comment]
Not sure if this fix caused it, but the initials are now positioned off-screen, and are thereby unusable.

![image](https://user-images.githubusercontent.com/1196524/61596726-89e8e180-ac07-11e9-9945-772242a24e9d.png)

Opening OP's url:

![image](https://user-images.githubusercontent.com/1196524/61596752-cc122300-ac07-11e9-8679-cd340e6e5382.png)

**Comment by FlorianKoerner** [comment]
@smeijer Which browser do you use?

**Comment by FlorianKoerner** [comment]
@smeijer Is it possible that the SVG file has been modified by an installed plugin? Actually there is no style- and link-tag in the SVG.

![screen](https://user-images.githubusercontent.com/647303/61596960-50fe3c00-ac0a-11e9-9f00-796d2b0149fc.PNG)

**Comment by smeijer** [comment]
Chrome 75.0.3770.100

Other browsers look better. Firefox seems to be perfect, Chrome is completely off, Edge and IE are positioned a bit too high.

```
Edge  | Chrome
IE 11 | Firefox
```


![image](https://user-images.githubusercontent.com/1196524/61596940-0c72a080-ac0a-11e9-80b9-ae938af8d999.png)

**Comment by smeijer** [comment]
That's quite interesting; `chrome --disable-extensions`, even the color changed 😕 	

![image](https://user-images.githubusercontent.com/1196524/61596980-80ad4400-ac0a-11e9-91a3-7439a928d557.png)

**Comment by smeijer** [comment]
I've disable every single extension that I have installed, but no difference.

Strange thing is, `chrome --disable-extensions` does show it correct. But chrome without user extensions still gives the same result. The DOM now equals yours:

I don't understand the color thing either. Does chrome itself have a color extensions build in?

![image](https://user-images.githubusercontent.com/1196524/61597099-35943080-ac0c-11e9-9dd7-1de13ece4183.png)

**Comment by FlorianKoerner** [comment]
I'm trying to fix it. I can reproduce the problems in IE/Edge.

**Comment by FlorianKoerner** [comment]
I have published a small update. Now everything looks identical in Firefox, Edge and Chrome.

![compare](https://user-images.githubusercontent.com/647303/61598255-0fc25800-ac1b-11e9-9e44-df7ea8cb9357.PNG)

@smeijer Does it work for you too? Can you find out which font your browser uses? Zomm 100%? Otherwise, can you copy the SVG source code here?

**Comment by smeijer** [comment]
Chrome, Firefox, Edge:

![image](https://user-images.githubusercontent.com/1196524/61616693-72424500-ac69-11e9-8ab2-88f04dae4940.png)

Zoom is `100%`

src:
```svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="isolation:isolate; background: #039BE5" viewBox="0 0 1 1" version="1.1">
  <text x="50%" y="50%" style="line-height: 1;  font-family: -apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,'Noto Sans',sans-serif; font-size: 0.5px" dy=".1em" alignment-baseline="middle" fill="#FFF" text-anchor="middle" dominant-baseline="middle">FK</text>
</svg>
```

```css
/**
 * SVG
 */
element.style {
    isolation: isolate;
    background: #039BE5;
}
/* user agent stylesheet */
svg:root {
    width: 100%;
    height: 100%;
}

/**
  * TEXT
  */
element.style {
    line-height: 1;
    font-family: -apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,'Noto Sans',sans-serif;
    font-size: 0.5px;
}

text[Attributes Style] {
    fill: rgb(255, 255, 255);
    text-anchor: middle;
    dominant-baseline: middle;
}

/* user agent stylesheet */
:not(svg) {
    transform-origin: 0px 0px;
}

/* user agent stylesheet */
text {
    display: block;
    white-space: nowrap;
}
```
